config/routes.rb
require 'resque/server'

Beanstock::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  mount Resque::Server.new, :at => "/resque"

  match "/login" => "sessions#new"
  match "/logout" => "sessions#destroy", :as => :logout
  match "/auth/linkedin/callback" => "sessions#create", provider: 'linkedin'
  match "/auth/:provider/callback" => "authorizations#create"

  namespace :signup do
    resources :experiences, :except => [:new, :create, :show]
    resources :users, :only => [:edit, :update]
    resources :skills, :except => [:new, :show]
    resources :beanstock_connections, :only => [:index, :create]
    resources :linkedin_connections, :only => [:index, :create]
  end

  match '/invitations' => 'invitations#update', :as => :invitations
  match 'audiences/autocomplete' => 'audiences#autocomplete', :as => :autocomplete_audiences
  match 'categories/autocomplete' => 'categories#autocomplete', :as => :autocomplete_categories
  match 'sites/autocomplete' => 'sites#autocomplete', :as => :autocomplete_sites
  match 'networks/autocomplete' => 'networks#autocomplete', :as => :autocomplete_networks

  resources :searches, :only => [:index] do
    collection do
      get :autocomplete
    end
  end

  match 'opportunity/1' => 'opportunities#show', :as => :demo_view_opportunity
  match 'opportunities' => 'opportunities#index'
  match 'opportunities/new' => 'opportunities#new', :as => :demo_new_opportunity

  resources :tools, :only => [:index, :show], :path => :connections do
    collection do
      get :new_entry
      get :nice_filter
      post :fine_fetch
    end
  end

  resources :activity_feeds, :only => :index

  resources :conversations, :only => [:index, :show, :new, :create], :path => :messages do
    collection do
      get :add_chat_message
      get :chat_history
      get :autocomplete
      get :archived
      get :window
      get :friend_preview_popup
    end
    member do
      post :quick_reply
      get :forward
      get :new_reply
      post :create_reply
      get :trash
      get :untrash
      get :archive
      get :unarchive
    end

  end

  resources :addresses, :except => [:index]
  resources :agencies do
    collection do
      get 'autocomplete'
    end
  end
  resources :brands do
    collection do
      get 'autocomplete'
    end
  end
  resources :advertisers do
    collection do
      get 'autocomplete'
    end
  end
  resources :buyers
  resources :publishers do
    resources :packages
  end
  resources :circles, :except => [:index, :show] do
    member do
      get 'add_user'
      get 'delete_user'
      get 'confirm_delete'
      get 'show_expanded'
    end
    collection do
      get 'collapse_expanded'
    end
  end
  resource :clicks
  resources :comments do
    resources :likes, :only => [:index, :create]
  end
  resources :answers do
    resources :likes, :only => [:index, :create]
  end
  resources :contacts, :except => [:index]
  resources :connections, :except => [:destroy], :path => :collaborate do
    collection do
      get 'add_contacts'
      get 'search'
    end
  end

  scope :module => "connections" do
    resources :manage_connections do
      collection do
        get "invite_users"
        get "co_workers"
        get "beanstock_connections"
        get "linkedin_connections"
      end
    end
    resources :my_connections do
      collection do
        get "all_connections"
        get "full_user_profile"
      end
    end
    resources :blocked_connections do
      collection do
        get "block_user"
        get "block_autocomplete_user"
        get "unblock_user"
        get "blocked_users"
      end
    end
    resources :ignored_connections
  end

  resources :experiences
  resources :user_profiles, :only => [:show] do
    member do
      get :edit_base_info
      put :update_base_info
      get :popup_profile
      post :update_photo
    end
    resources :viewings, :only => [:index]
  end
  resources :users, :only => [:show, :update] do
    collection do
      get 'show_users'
      get 'new_users_modal'
      get 'update_activity_feed'
      get 'search_friends'
      get 'update_status'
    end
    resources :authorizations
    resources :packages
  end
  resources :notices, :only => [:index, :destroy], :path => :notifications do
    collection do
      get :destroy_all
    end
  end
  resources :requests, :only => [:index]
  resources :suggestions, :only => :index
  resources :news, :as => "news_items", :only => [:index, :show] do
    resources :comments, :only => [:create, :destroy, :update]
    resources :likes, :only => [:index, :create]
    member do
      get :show_news, :as => :show
    end
  end
  match 'slide_elements' => 'news#slide_elements'
  match 'feeds' => 'news#feeds'
  match 'slide_news' => 'news#slide_news'
  resources :posts do
    resources :answers, :only => [:create, :destroy]
    resources :comments, :only => [:create, :destroy, :update]
    resources :likes, :only => [:index, :create]
  end
  resources :settings, except: [:new, :create, :destroy]
  resources :shares, only: [:create]
  resources :timeline_events do
    member do
      get :hide
    end
    collection do
      get :bulk_hide
      get :undo_bulk_hide
    end
  end
  resource :feature_requests, :controller => 'jira_issues', :only => [:new, :create], :type => 'FeatureRequest'
  resource :support_requests, :controller => 'jira_issues', :only => [:new, :create], :type => 'SupportRequest'

  match 'home' => 'users#show'

  root :to => "tools#index"

  unless Rails.env.production?
    match "/all_logins" => "logins#index"
    match "/simulate_login/:id" => "logins#simulate_login", :as => :simulate_login
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  layout "discover", :only => [:index, :show]

  before_filter :fetch_inbox_messages, :only => [:index]
  before_filter :find_conversation, :only => [:show, :create_reply, :trash, :untrash, :archive, :unarchive, :forward, :new_reply, :quick_reply]
  before_filter :find_chat_conversation, :only => [:add_chat_message, :chat_history]

  def index
    @conversations = regularize_conversations(@conversations)
  end

  def show
    current_user.mark_as_read(@conversation)
  end

  def create
    recipients_ids = params[:message][:recipients_ids].split(',')
    recipients = User.find_all_by_id(recipients_ids)
    subject = params[:message][:subject].blank? ? I18n.t("conversation.no_subject") : params[:message][:subject]
    @message = current_user.create_message(recipients,
                                              params[:message][:body],
                                              subject,
                                              true,
                                              params[:message][:attachment]
                                             )
    @conversation = @message.deliver.conversation
    if @conversation
      respond_to do |format|
        format.js
      end
    else
      render :action => :new
    end
  end

  def add_chat_message
    @conversation = current_user.send_or_reply_to_conversation(@conversation, params[:message], @friend)
    @message = @conversation.messages.last
    @friend.mark_as_read(@conversation) if @friend.online?
  end

  def chat_history
    @messages = @conversation.messages
  end

  def forward
    @message = @conversation.forward_message(params[:message_id])
    respond_to do |format|
      format.js
    end
  end

  def new_reply
    @message = Message.new
    @recipient = @conversation.originator
    respond_to do |format|
      format.js
    end
  end

  def create_reply
    @message = current_user.reply_to_conversation(@conversation,
                                                 params[:message][:body],
                                                 params[:message][:subject],
                                                 true,
                                                 true,
                                                 params[:message][:attachment]
                                                 ).message
    if @message
      respond_to do |format|
        format.js
      end
    else
      render :action => :new_reply
    end
  end

  def quick_reply
    @message = current_user.reply_to_conversation(@conversation,
                                                 params[:message][:body],
                                                 params[:message][:subject],
                                                 true,
                                                 true,
                                                 params[:message][:attachment]
                                                 ).message
    if @message
      respond_to do |format|
        format.js
      end
    else
      render :action => :show
    end
  end

  def archive
    current_user.mark_as_archived(@conversation)
    respond_to do |format|
      format.js
    end
  end

  def unarchive
    current_user.unarchive(@conversation)
    @conversations = regularize_conversations(Conversation.archived_for_user(current_user))
    respond_to do |format|
      format.js
    end
  end

  def trash
    @conversation.move_to_trash(current_user)
    respond_to do |format|
      format.js
    end
  end

  def untrash
    @conversation.untrash(current_user)
  end

  def autocomplete
    friends = current_user.my_friends.search(params[:term])
    render :json => friends.map{ |b| { :id => b.id, :value => b.fullname } }
  end

  def new
    @message = Message.new
    @recipient = User.find_by_id(params[:recipient_id])
  end

  def window
    @friend = User.find_by_id(params[:friend_id])
    render :layout => false
  end

  def archived
    @conversations = regularize_conversations(Conversation.archived_for_user(current_user))
    respond_to do |format|
      format.js
    end
  end

  def friend_preview_popup
    @friend = User.find(params[:friend_id])
    render :partial => 'layouts/my_marketplace/friend_preview'
  end

  private

  def find_conversation
    @conversation ||= current_user.conversations.find(params[:id])
  end

  def find_chat_conversation
    @friend = User.find(params[:friend_id])
    @conversation = Conversation.chat_conversations_between(@friend, current_user).first
  end

  def fetch_inbox_messages
    @conversations = current_user.conversations.page(params[:page]).per(Constants::Messages::CONVERSATIONS_PER_PAGE)
  end

  def regularize_conversations(conversations)
    cnvs = conversations.select { |conversation| !conversation.is_trashed?(current_user) } #remove trashed conversations
    cnvs = cnvs.select { |conversation| !current_user.is_archived?(conversation) } if params[:action] != 'archived' && params[:action] != 'unarchive'
    if params[:sort].present? && params[:sort] == 'from_old_to_new'
      cnvs = cnvs.sort_by(&:updated_at)
    end
    cnvs = cnvs.select { |conversation| conversation.originator.role.id.to_s == params[:role_id] } if params[:role_id].present?
    cnvs
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
  def message_status_img(conversation)
    content_tag(:i, "", :class => "img-unread") if unread?(conversation)
  end

  def unread(conversation)
    "unread" if unread?(conversation)
  end

  def generate_chat_id(user_id, friend_id)
    if user_id < friend_id.to_i
      "/#{user_id}_#{friend_id}"
    else
      "/#{friend_id}_#{user_id}"
    end
  end

  def broadcast(channel, &block)
    message = {:channel => channel, :data => capture(&block), :ext => {:auth_token => FAYE_TOKEN}}
    uri = URI.parse("http://localhost:9292/faye")
    Net::HTTP.post_form(uri, :message => message.to_json)
  end

  def message_owner_class(chat_message)
    current_user == chat_message.sender ? 'self_message' : 'friend_message'
  end

  def recognize_controller_name_by_path(path)
    Rails.application.routes.recognize_path(path)[:controller]
  end

  def link_for_submit
    link ||= conversations_path
  end

  private

  def unread?(conversation)
    current_user.mailbox.inbox.unread(current_user).include?(conversation) ? true : false
  end

end

app/views/conversations/_actions_bar.html.erb
<div id="actions_bar">
  <%= render :partial => 'messages_menu' %>
  <%= render :partial => 'actions_menu' %>
</div>

app/views/conversations/_actions_menu.html.erb
<div class="row-fluid actions-menu">
  <div class="span6">
    <div>
      <%= text_field_tag :search_message, params[:search], :class => "search-query", "placeholder" => "#{ t('.search_messages') }" %>
    </div>
  </div>
  <div id="sort_by_old" class="btn-group span3 filter_by">
    <button class="btn dropdown-toggle" data-toggle="dropdown" href="#">
      <div class="current-value" data-value="" style="float: left; margin-right: 10px;"><%= Constants::Messages::SORT.first[1] %></div>
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
      <% Constants::Messages::SORT.each do |key, value| %>
        <li>
          <%= link_to value, conversations_path(:sort => key), "data-value" => key, :id => key, :remote => true %>
        </li>
      <% end %>
    </ul>
  </div>
  <div id="filter_by_user_role" class="btn-group span3 filter_by">
    <button class="btn dropdown-toggle" data-toggle="dropdown" href="#">
      <div class="current-value" data-value="" style="float: left; margin-right: 10px;"><%= t('.all') %></div>
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
      <li>
        <%= link_to t('.all'), conversations_path, "data-value" => t('.all'), :id => t('.all'), :remote => true %>
      </li>
      <% Role.all.each do |role| %>
        <li>
          <%= link_to role.name.capitalize, conversations_path(:role_id => role.id), "data-value" => role.name, :id => role.name, :remote => true %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/conversations/_conversation.html.erb
<tr id="conversation_<%= conversation.id %>" class="<%= unread(conversation) %>">
  <td class="avatar">
    <%= link_to image_tag(conversation.originator.logo, :size => "48x48"), user_profile_path(conversation.originator.user_profile), :class => "user-profile-img" %>
  </td>
  <td class="view-message-info">
    <div class="info">
      <div class="full-name"><%= link_to conversation.originator.fullname, user_profile_path(conversation.originator.user_profile), :class => "name user-profile" %></div>
      <div class="close_button">
        <div class="icons">
          <%= link_to '#', :onclick => "Conversation.sendToConversation('#{ trash_conversation_path(conversation) }'); return false;" do %>
            <i class="img-remove"></i>
          <% end %>
        </div>
      </div>
    </div>
    <div class="message-subject <%= unread(conversation) %>">
      <%= t(".subject") %> <%= link_to conversation.last_message.subject, conversation_path(conversation) %>
    </div>
    <div class="user-role">
      <div class="role"><%= conversation.originator.role.name.capitalize %></div>
      <div class="close_button">
        <div class="icons">
          <%= render :partial => "archive_unarchive_conversation", :locals => { :conversation => conversation } %>
          <%= message_status_img(conversation) %>
        </div>
      </div>
    </div>
    <div class="short-message">
      <%= link_to conversation_path(conversation) do %>
        <%= truncate(conversation.last_message.body, :length => 70) %>
      <% end %>
      <div><%= receiving_date(conversation.last_message) %></div>
    </div>
  </td>
</tr>

app/views/conversations/_message.html.erb
<tr id="<%= message.id %>" class="message-row <% "unread(conversation, last_message)" %>">
  <td class="avatar">
    <%= link_to image_tag(message.sender.user_profile.avatar.thumb.url, :size => "48x48"), user_profile_path(message.sender.user_profile), :class => "user-profile-img" %>
  </td>
  <td class="view-message-info">
    <div class="author-name <%= cycle('dark', 'red') %>">
      <%= link_to message.sender.fullname, user_profile_path(message.sender.user_profile), :class => "name user-profile" %>
    </div>
    <div class="info">
      <div class="message-subject <% "unread(conversation, last_message)" %>">
        <%= message.subject %>
      </div>
      <div class="short-message">
        <%= message.body %>
      </div>
    </div>
  </td>
  <td>
    <div class="message-created-at"><%= receiving_date(message) %></div>
    <% if message.attachment.present? %>
      <%= link_to message.attachment.url do %>
        <div class="attachment">
          <i class="img-attach"></i>
        </div>
      <% end %>
    <% end %>
  </td>
</tr>

app/views/conversations/_messages.html.erb
<table id="messages">
  <%= render :partial => 'message', :collection => @conversation.messages %>
</table>
<%= render :partial => 'quick_reply_form', :locals => { :conversation => @conversation } %>

app/views/conversations/_untrash.html.erb
<tr id="conversation_<%= @conversation.id %>" class="undelete">
  <td class="avatar">
    <%= link_to image_tag(@conversation.originator.logo, :size => "48x48"), user_profile_path(@conversation.originator.user_profile), :class => "user-profile-img" %>
  </td>
  <td class="view-message-info">
    <div class="info">
      <div class="full-name"><%= link_to @conversation.originator.fullname, user_profile_path(@conversation.originator.user_profile), :class => "name user-profile" %></div>
    </div>
    <p></p>
    <div class="delete-message">
      <div><%= t(".message_deleted") %> <%= link_to t('.undelete'), untrash_conversation_path(@conversation), :remote => true %></div>
      <div><%= receiving_date(@conversation.last_message) %></div>
    </div>
  </td>
</tr>

app/views/conversations/_window_chat.html.erb
<div id="friend_chat_<%= friend.id %>" class="friend_chat span12" data-message-url="<%= add_chat_message_conversations_url %>" data-friend-id="<%= friend.id %>">
  <div class="row-fluid header_part">
    <div class="friend_logo">
      <%= link_to image_tag(friend.user_profile.avatar.thumb.url, :size => "40x40", :class => "friend_avatar" ), user_profile_path(friend.user_profile), :target => "_blank" %>
    </div>
    <div class="friend_info">
      <div class="<%= status_class(friend.online_status) %> status_icon"></div>
      <p class="friend_name">
        <%= friend.fullname %>
      </p>
      <p class="last_seen">
        <%= last_seen(friend) %>
      </p>
    </div>
    <div class="to-normal"></div>
  </div>
  <div class="row-fluid conversations_part">
  </div>
  <div class="row-fluid messages_part">
    <%= text_area_tag :chat_message, '', :placeholder => t('.type_message_here'), :rows => 3 %>
    <%= link_to t('.show_messages_history'), chat_history_conversations_path(:friend_id => friend.id), :remote => true %>
  </div>
</div>

app/views/conversations/archived.js.erb
$('#conversations_container').html("<%= j(render :partial => 'conversations') %>");
Conversation.updateFiltersLinks("<%= archived_conversations_path %>");
Conversation.refreshNiceScroll();

app/views/conversations/create.js.erb
Conversation.newMessageClose();

app/views/conversations/create_reply.js.erb
$("#bootstrap_modal").modal('hide');

app/views/conversations/forward.js.erb
$("#bootstrap_modal").html("<%= j(render :partial =>'form') %>");
$("#bootstrap_modal").modal();

app/views/conversations/index.html.erb
<%= render :partial => 'shared/inbox_tabs' %>
<div id="body_conversations" class="tab-content inbox_tab_content">
  <div class="tab-pane active" id="show_notifications">
    <%= render :partial => 'actions_bar' %>
    <div id="conversations_container">
      <%= render :partial => "conversations" %>
    </div>
  </div>
</div>

app/views/conversations/trash.js.erb
$("#conversation_<%= @conversation.id %>").replaceWith("<%= j(render :partial => 'untrash') %>");

app/views/conversations/unarchive.js.erb
$('#conversations_container').html("<%= j(render :partial => 'conversations') %>");