config/routes.rb
require 'resque/server'

Beanstock::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  mount Resque::Server.new, :at => "/resque"

  match "/login" => "sessions#new"
  match "/logout" => "sessions#destroy", :as => :logout
  match "/auth/linkedin/callback" => "sessions#create", provider: 'linkedin'
  match "/auth/:provider/callback" => "authorizations#create"

  namespace :signup do
    resources :experiences, :except => [:new, :create, :show]
    resources :users, :only => [:edit, :update]
    resources :skills, :except => [:new, :show]
    resources :beanstock_connections, :only => [:index, :create]
    resources :linkedin_connections, :only => [:index, :create]
  end

  match '/invitations' => 'invitations#update', :as => :invitations
  match 'audiences/autocomplete' => 'audiences#autocomplete', :as => :autocomplete_audiences
  match 'categories/autocomplete' => 'categories#autocomplete', :as => :autocomplete_categories
  match 'sites/autocomplete' => 'sites#autocomplete', :as => :autocomplete_sites
  match 'networks/autocomplete' => 'networks#autocomplete', :as => :autocomplete_networks

  resources :searches, :only => [:index] do
    collection do
      get :autocomplete
    end
  end

  match 'opportunity/1' => 'opportunities#show', :as => :demo_view_opportunity
  match 'opportunities' => 'opportunities#index'
  match 'opportunities/new' => 'opportunities#new', :as => :demo_new_opportunity

  resources :tools, :only => [:index, :show], :path => :connections do
    collection do
      get :new_entry
      get :nice_filter
      post :fine_fetch
    end
  end

  resources :activity_feeds, :only => :index

  resources :conversations, :only => [:index, :show, :new, :create], :path => :messages do
    collection do
      get :add_chat_message
      get :chat_history
      get :autocomplete
      get :archived
      get :window
      get :friend_preview_popup
    end
    member do
      post :quick_reply
      get :forward
      get :new_reply
      post :create_reply
      get :trash
      get :untrash
      get :archive
      get :unarchive
    end

  end

  resources :addresses, :except => [:index]
  resources :agencies do
    collection do
      get 'autocomplete'
    end
  end
  resources :brands do
    collection do
      get 'autocomplete'
    end
  end
  resources :advertisers do
    collection do
      get 'autocomplete'
    end
  end
  resources :buyers
  resources :publishers do
    resources :packages
  end
  resources :circles, :except => [:index, :show] do
    member do
      get 'add_user'
      get 'delete_user'
      get 'confirm_delete'
      get 'show_expanded'
    end
    collection do
      get 'collapse_expanded'
    end
  end
  resource :clicks
  resources :comments do
    resources :likes, :only => [:index, :create]
  end
  resources :answers do
    resources :likes, :only => [:index, :create]
  end
  resources :contacts, :except => [:index]
  resources :connections, :except => [:destroy], :path => :collaborate do
    collection do
      get 'add_contacts'
      get 'search'
    end
  end

  scope :module => "connections" do
    resources :manage_connections do
      collection do
        get "invite_users"
        get "co_workers"
        get "beanstock_connections"
        get "linkedin_connections"
      end
    end
    resources :my_connections do
      collection do
        get "all_connections"
        get "full_user_profile"
      end
    end
    resources :blocked_connections do
      collection do
        get "block_user"
        get "block_autocomplete_user"
        get "unblock_user"
        get "blocked_users"
      end
    end
    resources :ignored_connections
  end

  resources :experiences
  resources :user_profiles, :only => [:show] do
    member do
      get :edit_base_info
      put :update_base_info
      get :popup_profile
      post :update_photo
    end
    resources :viewings, :only => [:index]
  end
  resources :users, :only => [:show, :update] do
    collection do
      get 'show_users'
      get 'new_users_modal'
      get 'update_activity_feed'
      get 'search_friends'
      get 'update_status'
    end
    resources :authorizations
    resources :packages
  end
  resources :notices, :only => [:index, :destroy], :path => :notifications do
    collection do
      get :destroy_all
    end
  end
  resources :requests, :only => [:index]
  resources :suggestions, :only => :index
  resources :news, :as => "news_items", :only => [:index, :show] do
    resources :comments, :only => [:create, :destroy, :update]
    resources :likes, :only => [:index, :create]
    member do
      get :show_news, :as => :show
    end
  end
  match 'slide_elements' => 'news#slide_elements'
  match 'feeds' => 'news#feeds'
  match 'slide_news' => 'news#slide_news'
  resources :posts do
    resources :answers, :only => [:create, :destroy]
    resources :comments, :only => [:create, :destroy, :update]
    resources :likes, :only => [:index, :create]
  end
  resources :settings, except: [:new, :create, :destroy]
  resources :shares, only: [:create]
  resources :timeline_events do
    member do
      get :hide
    end
    collection do
      get :bulk_hide
      get :undo_bulk_hide
    end
  end
  resource :feature_requests, :controller => 'jira_issues', :only => [:new, :create], :type => 'FeatureRequest'
  resource :support_requests, :controller => 'jira_issues', :only => [:new, :create], :type => 'SupportRequest'

  match 'home' => 'users#show'

  root :to => "tools#index"

  unless Rails.env.production?
    match "/all_logins" => "logins#index"
    match "/simulate_login/:id" => "logins#simulate_login", :as => :simulate_login
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  layout 'search'

	helper_method :check_filter_params

  before_filter :ensure_params_provided, :only => :autocomplete
  before_filter :check_search_params

  def index
    search
  end

  def autocomplete
    @search_text = params[:term]
    render :json => Search::Results::Formatter.new(search).to_autocompete_json
  end

  private

  def check_search_params
    @filter_param = params[:filter] ? params[:filter].downcase.to_sym : :all
    @search_text = params[:search] || ''
    @limit = params[:rows] || 0
  end

  def ensure_params_provided
    render(:json => {:error => 'Bad request.'}, :status => :bad_request) unless params[:term].present?
  end

  def search
    if Constants::Search::FILTER.has_key?(@filter_param) && @search_text.present?
      @search ||= Sunspot::Searching.new(@filter_param, @search_text)
      @search_results ||= @search.produce_search(:limit => @limit)
    end
  end

	def check_filter_params
		params[:filter] || I18n.t(:all)
	end

end

app/helpers/searches_helper.rb
module SearchesHelper
  def results_for(search_text)
    content_tag :p, t('searches.index.search_results_for', :search_for => search_text) unless search_text.empty?
  end
end

app/views/searches/_agencies.html.erb
<% results.each do |result|%>
  <tr class=<%= "found-agencies" %>>
    <td>
      <%= link_to (image_tag(result.logo.thumb.url, :width => 48, :height => 48)), tool_path(result) %>
      <div class='connection-details'>
        <div class='author'>
          <%= link_to result.name, tool_path(result) %>
        </div>
        <div class='divider'></div>
        <div class='description'><%= result.description %></div>
      </div>
    </td>
    <td>
      <%= link_to t(".view_profile"), tool_path(result), :class => "btn btn-small" %>
    </td>
  </tr>
<% end %>

app/views/searches/_brands.html.erb
<% results.each do |result|%>
  <tr class=<%= "found-brands" %>>
    <td>
      <%= link_to (image_tag(result.logo.thumb.url, :width => 48, :height => 48)), tool_path(result) %>
      <div class='connection-details'>
        <div class='author'>
          <%= link_to result.name, tool_path(result) %>
        </div>
        <div class='divider'></div>
        <div class='description'><%= result.description %></div>
      </div>
    </td>
    <td>
      <%= link_to t(".view_profile"), tool_path(result), :class => "btn btn-small" %>
    </td>
  </tr>
<% end %>

app/views/searches/_companies.html.erb
<% results.each do |result|%>
  <tr class=<%= "found-companies" %>>
    <td>
      <%= link_to (image_tag(result.logo.thumb.url, :width => 48, :height => 48)), tool_path(result) %>
      <div class='connection-details'>
        <div class='author'>
          <%= link_to result.name, tool_path(result) %>
        </div>
        <div class='divider'></div>
        <div class='description'><%= result.description %></div>
      </div>
    </td>
    <td>
      <%= link_to t(".view_profile"), tool_path(result), :class => "btn btn-small" %>
    </td>
  </tr>
<% end %>

app/views/searches/_people.html.erb
<% results.each do |result|%>
  <tr class=<%= "found-people" %>>
    <td>
      <%= link_to (image_tag(result.user_profile_avatar, :width => 48, :height => 48)), user_profile_path(result.user_profile) %>
      <div class='connection-details'>
        <div class='author'>
          <%= link_to result.fullname, user_profile_path(result.user_profile) %>
          <span class='user-role <%= result.user_type %>'><%= result.humanable_role %></span>
        </div>
        <div class='status'><%= result.online_status %></div>
        <div class='description'><%= result.user_profile_title %></div>
      </div>
    </td>
    <td>
      <%= render_view_profile(result) %>
      <%= request_connection_link(result) %>
    </td>
  </tr>
<% end %>

app/views/searches/_posts.html.erb
<% results.each do |result|%>
  <tr class=<%= "found-posts" %>>
    <td>
      <%= link_to (image_tag(result.user_profile_avatar, :width => 48, :height => 48)), user_profile_path(result.user_profile) %>
      <div class='connection-details'>
        <div class='author'>
          <%= link_to result.user_fullname, user_profile_path(result.user_profile) %>
          <span class='user-role <%= result.user.user_type %>'><%= result.user.humanable_role %><span>
        </div>
        <div class='status'><%= result.online_status %></div>
        <div class='description'><%= result.title %></div>
      </div>
    </td>
    <td>
      <%= link_to t("view"), post_path(result), :class => "btn btn-small" %>
    </td>
  </tr>
<% end %>

app/views/searches/_results_table.html.erb
<% if @search.found? %>
  <table>
    <% search_results.each do |key, value| %>
      <% unless key == :search_text || value.empty? %>
        <%= render :partial => key.to_s, :locals => { :results => value, :type => key } %>
      <% end %>  
    <% end %>  
  </table>
<% else %>
  <p><%= "#{ t('.no_results') } #{search_results[:search_text]}" %></p>
<% end %>

app/views/searches/_search_form_with_filter.html.erb
<%= form_tag searches_path, :method => :get, :id => 'inline-search', :autocomplete => 'off' do %>
  <%= select_tag :filter, options_for_select(Constants::Search::FILTER, check_filter_params), :class => 'hidden' %>
  <div id="select-search-type" class="btn-group">
    <button class="btn dropdown-toggle-search all-rounded" data-toggle="dropdown" href="#">
      <div class="current-value"><%= check_filter_params %></div>
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
      <%= render_search_filter_options %>
    </ul>
  </div>
  <%= text_field_tag :search, params[:search], :class => "search-query span2",
    :placeholder => "#{ t('.type_your_search_here') }",
    :onkeypress => 'javascript:Search.submit_form(event)',
    :data => {:autocomplete_source => autocomplete_searches_path} %>
<% end %>

app/views/searches/index.html.erb
<div class="row-fluid">
  <div class="span6">
    <div class='search-header'>
      <% if @search_results %>
        <h3>
          <%= image_tag "icons/search-bg.png", :class => "search-glass" %>
          <%= t('.search_results') %>
        </h3>
        <%= results_for(@search_results[:search_text]) %>
      <% end %>
    </div>
  </div>
  <div class="span6">
    <div class='inline-search-form pull-right'>
      <%= render :partial => "search_form_with_filter" %>
    </div>
  </div>
</div>

<div class='search-results'>
  <% if @search_results %>
    <%= render :partial => "results_table", :locals => { :search_results => @search_results } %>
  <% else %>
    <p><%= t('.empty_query') %></p>
  <% end %>
</div>