config/routes.rb
require 'resque/server'

Beanstock::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  mount Resque::Server.new, :at => "/resque"

  match "/login" => "sessions#new"
  match "/logout" => "sessions#destroy", :as => :logout
  match "/auth/linkedin/callback" => "sessions#create", provider: 'linkedin'
  match "/auth/:provider/callback" => "authorizations#create"

  namespace :signup do
    resources :experiences, :except => [:new, :create, :show]
    resources :users, :only => [:edit, :update]
    resources :skills, :except => [:new, :show]
    resources :beanstock_connections, :only => [:index, :create]
    resources :linkedin_connections, :only => [:index, :create]
  end

  match '/invitations' => 'invitations#update', :as => :invitations
  match 'audiences/autocomplete' => 'audiences#autocomplete', :as => :autocomplete_audiences
  match 'categories/autocomplete' => 'categories#autocomplete', :as => :autocomplete_categories
  match 'sites/autocomplete' => 'sites#autocomplete', :as => :autocomplete_sites
  match 'networks/autocomplete' => 'networks#autocomplete', :as => :autocomplete_networks

  resources :searches, :only => [:index] do
    collection do
      get :autocomplete
    end
  end

  match 'opportunity/1' => 'opportunities#show', :as => :demo_view_opportunity
  match 'opportunities' => 'opportunities#index'
  match 'opportunities/new' => 'opportunities#new', :as => :demo_new_opportunity

  resources :tools, :only => [:index, :show], :path => :connections do
    collection do
      get :new_entry
      get :nice_filter
      post :fine_fetch
    end
  end

  resources :activity_feeds, :only => :index

  resources :conversations, :only => [:index, :show, :new, :create], :path => :messages do
    collection do
      get :add_chat_message
      get :chat_history
      get :autocomplete
      get :archived
      get :window
      get :friend_preview_popup
    end
    member do
      post :quick_reply
      get :forward
      get :new_reply
      post :create_reply
      get :trash
      get :untrash
      get :archive
      get :unarchive
    end

  end

  resources :addresses, :except => [:index]
  resources :agencies do
    collection do
      get 'autocomplete'
    end
  end
  resources :brands do
    collection do
      get 'autocomplete'
    end
  end
  resources :advertisers do
    collection do
      get 'autocomplete'
    end
  end
  resources :buyers
  resources :publishers do
    resources :packages
  end
  resources :circles, :except => [:index, :show] do
    member do
      get 'add_user'
      get 'delete_user'
      get 'confirm_delete'
      get 'show_expanded'
    end
    collection do
      get 'collapse_expanded'
    end
  end
  resource :clicks
  resources :comments do
    resources :likes, :only => [:index, :create]
  end
  resources :answers do
    resources :likes, :only => [:index, :create]
  end
  resources :contacts, :except => [:index]
  resources :connections, :except => [:destroy], :path => :collaborate do
    collection do
      get 'add_contacts'
      get 'search'
    end
  end

  scope :module => "connections" do
    resources :manage_connections do
      collection do
        get "invite_users"
        get "co_workers"
        get "beanstock_connections"
        get "linkedin_connections"
      end
    end
    resources :my_connections do
      collection do
        get "all_connections"
        get "full_user_profile"
      end
    end
    resources :blocked_connections do
      collection do
        get "block_user"
        get "block_autocomplete_user"
        get "unblock_user"
        get "blocked_users"
      end
    end
    resources :ignored_connections
  end

  resources :experiences
  resources :user_profiles, :only => [:show] do
    member do
      get :edit_base_info
      put :update_base_info
      get :popup_profile
      post :update_photo
    end
    resources :viewings, :only => [:index]
  end
  resources :users, :only => [:show, :update] do
    collection do
      get 'show_users'
      get 'new_users_modal'
      get 'update_activity_feed'
      get 'search_friends'
      get 'update_status'
    end
    resources :authorizations
    resources :packages
  end
  resources :notices, :only => [:index, :destroy], :path => :notifications do
    collection do
      get :destroy_all
    end
  end
  resources :requests, :only => [:index]
  resources :suggestions, :only => :index
  resources :news, :as => "news_items", :only => [:index, :show] do
    resources :comments, :only => [:create, :destroy, :update]
    resources :likes, :only => [:index, :create]
    member do
      get :show_news, :as => :show
    end
  end
  match 'slide_elements' => 'news#slide_elements'
  match 'feeds' => 'news#feeds'
  match 'slide_news' => 'news#slide_news'
  resources :posts do
    resources :answers, :only => [:create, :destroy]
    resources :comments, :only => [:create, :destroy, :update]
    resources :likes, :only => [:index, :create]
  end
  resources :settings, except: [:new, :create, :destroy]
  resources :shares, only: [:create]
  resources :timeline_events do
    member do
      get :hide
    end
    collection do
      get :bulk_hide
      get :undo_bulk_hide
    end
  end
  resource :feature_requests, :controller => 'jira_issues', :only => [:new, :create], :type => 'FeatureRequest'
  resource :support_requests, :controller => 'jira_issues', :only => [:new, :create], :type => 'SupportRequest'

  match 'home' => 'users#show'

  root :to => "tools#index"

  unless Rails.env.production?
    match "/all_logins" => "logins#index"
    match "/simulate_login/:id" => "logins#simulate_login", :as => :simulate_login
  end
end

app/models/companies/brand.rb
class Brand < Company

  has_many :agency_brands
  has_many :agencies, :through => :agency_brands
  has_many :brand_advertisers
  has_many :advertisers, :through => :brand_advertisers

  validate :agency_presence
  validate :advertiser_presence

  accepts_nested_attributes_for :agency_brands, :reject_if => proc { |attributes| attributes['agency_name'].blank? }
  accepts_nested_attributes_for :brand_advertisers, :reject_if => proc { |attributes| attributes['advertiser_name'].blank? }

  fires :midb_brand_created, :on    => :create,
                             :actor => :owner,
                             :type  => proc { 'TimelineEvents::MidbCompanyCreated' }

  fires :midb_brand_updated, :on    => :update,
                             :actor => :owner,
                             :fields_changes => :fields_changed,
                             :type  => proc { 'TimelineEvents::MidbCompanyUpdated' }

  fires :midb_brand_deleted, :on    => :destroy,
                             :actor => :owner,
                             :type  => proc { 'TimelineEvents::MidbCompanyDeleted' }

  scope :search, lambda { |search|
    where("LOWER(name) LIKE '%#{search.downcase}%'") if search.present?
  }

  scope :order_by_name, lambda { |order|
    order("name #{order || 'ASC'}")
  }

  scope :fine_search, lambda { |params| by_categories(params[:category_ids]).by_cities(params[:cities]) }

  searchable do
    text :name
  end

  def self.expanded_company
    instance = super
    instance.agency_brands.build
    instance.brand_advertisers.build
    instance
  end

  def company_items_for_profile
    [agencies.limit(Company::TILES_NUMBER_FOR_PROFILE), advertisers.limit(Company::TILES_NUMBER_FOR_PROFILE)]
  end

  def brand?
    true
  end

  private

  def agency_presence
    agency_brands.each do |agency_brand|
      if agency_brand.agency_id.nil?
        errors.add(:agencies, :agency_do_not_exist)
      end
    end
  end

  def advertiser_presence
    brand_advertisers.each do |brand_advertiser|
      if brand_advertiser.advertiser_id.nil?
        errors.add(:advertisers, :advertiser_do_not_exist)
      end
    end
  end
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController

  def index
    @company = Company.find(params[:company]) if params[:company]
    @brands = if @company
                  @company.brands.search(params[:search]).order_by_name(params[:order])
                else
                  Brand.search(params[:search]).order_by_name(params[:order])
                end
  end

  def new
    @brand = Brand.expanded_company
    respond_to do |format|
      format.js
    end
  end

  def create
    @brand = Brand.new(params[:brand])
    @brand.owner = current_user

    respond_to do |format|
      if @brand.save
        format.js
        format.html { redirect_to tools_path, :notice => I18n.t('brands.create.success') }
        format.json { render :json => @brand, :status => :created, :location => @brand }
      else
        @brand.agency_brands.new if @brand.agency_brands.empty?
        @brand.brand_advertisers.new if @brand.brand_advertisers.empty?
        format.js
        format.html { render :action => "new" }
        format.json { render :json => @brand.errors, :status => :unprocessable_entity }
      end
    end
  end

  def autocomplete
    @brands = Brand.joins(:brand_advertisers).where("companies.name like ? AND brand_advertisers.advertiser_id in (?)", "%#{params[:term]}%", params[:ids].split(",")).group("companies.id").order("companies.name")
    render :json => @brands.map{|b| {:id => b.id, :value => b.name}}
  end

end

app/views/brands/_associations.html.erb
<div id="add-associations-brand" class="tab-pane associations">
  <div class="control-group">
    <%= label_tag "agency_brands__name", t('.agencies'), :class => 'control-label' %>
    <div class="controls">
      <div class="inputs">
        <%= f.fields_for :agency_brands do |brand_agency| %>
          <div class="brand_agency association">
            <%= brand_agency.hidden_field :agency_id, :class => "object_id" %>
            <%= brand_agency.hidden_field :_destroy, "data-type" => "destroy_input" %>
            <%= brand_agency.text_field :agency_name, :class => "input-large object_name", :data => {:autocomplete_source => autocomplete_agencies_path} %>
            <div class="delete_association link inline_block close">×</div>
          </div>
        <% end %>
      </div>
      <p class="help_block"><%= t('.agency_info') %></p>
    </div>
    <div class="controls link" id="add_brand_agency">
      <%= t('.add_another_agency') %>
    </div>
  </div>

  <div class="control-group">
    <%= label_tag "brand_advertisers__name", t('.advertisers'), :class => 'control-label' %>
    <div class="controls">
      <div class="inputs">
        <%= f.fields_for :brand_advertisers do |brand_advertiser| %>
          <div class="brand_advertiser association">
            <%= brand_advertiser.hidden_field :advertiser_id, :class => "object_id" %>
            <%= brand_advertiser.hidden_field :_destroy, "data-type" => "destroy_input" %>
            <%= brand_advertiser.text_field :advertiser_name, :class => "input-large object_name", :data => {:autocomplete_source => autocomplete_advertisers_path} %>
            <div class="delete_association link inline_block close">×</div>
          </div>
        <% end %>
      </div>
      <p class="help_block"><%= t('.advertiser_info') %></p>
    </div>
    <div class="controls link" id="add_brand_advertiser">
      <%= t('.add_another_advertiser') %>
    </div>
  </div>
</div>

<script type="text/javascript">
  process_associations(['brand_advertiser', 'brand_agency']);
</script>

app/views/brands/_brand.html.erb
<div class="modal-header">
  <button class="close" data-dismiss="modal" type="button">×</button>
  <h3><%= t('.add_new_brand') %></h3>
</div>
<div class="modal-body">
  <div class="form_container" id="brand_form">
    <%= render :partial => "brands/form" %>
  </div>
</div>
<div class="modal-footer">
  <button class="button violet" id="submit_button"><%= t('save_and_add') %></button>
  <a data-dismiss="modal" class="button" href="#"><%= t('cancel') %></a>
</div>

<script type="text/javascript">

  $("#submit_button").click(function(event){
    $("#new_brand").submit();
    event.preventDefault();
  });
</script>

app/views/brands/_form.html.erb
<%= form_for(@brand, :html => { :class => "brand nice", :remote => true }, :builder => StandartBuilder) do |f| %>
  <%= render :partial => 'brands/navigation' %>
  <div class="tab-content">
    <%= render :partial => 'tools/basic', :locals => { :f => f, :company => @brand } %>
    <%= render :partial => 'brands/associations', :locals => { :f => f } %>
    <%= render :partial => 'tools/description', :locals => { :f => f, :company => @brand } %>
  </div>
<%end%>

app/views/brands/_navigation.html.erb
<ul class="nav nav-tabs">
  <li class="active"><a data-toggle="tab" href="#add-basic-brand"><%= t('.basic_details') %></a></li>
  <li><a data-toggle="tab" href="#add-associations-brand"><%= t('.associations') %></a></li>
  <li><a data-toggle="tab" href="#add-description-brand"><%= t('.other_details') %></a></li>
</ul>

app/views/brands/_new.html.erb
<%= render :partial => "form", :locals => {:header => t('.add_entry'), :submit_button_text => t('add')} %>

app/views/brands/create.js.erb
<% if @brand.errors.empty? %>
  $newItem = $('<%= escape_javascript(render :partial => 'tools/item', :locals => { :item => @brand.locations.first, :type => 'brand'})%>');
  $('table#profile_list tbody').append($newItem);
  Marketplace.data_items.push(<%= @brand.locations.first.to_json(:only => :id, :methods => %w(fullname discover_location discover_type)).html_safe %>);
  $("table#profile_list").tablesorter({ sortList: [[0,0]] });
  serch_profile($('input#discover-search').val());
  $('#bootstrap_modal').modal('hide');
<% else %>
  $("#brand_form").html("<%= escape_javascript(render :partial =>'form')%>");
<% end %>

app/views/brands/index.html.erb
<ul class="breadcrumb">
  <li>
    <%= link_to t(".build_marketplace"), tools_path %>
    <span class="divider">/</span>
  </li>
  <%- if @company %>
    <li>
      <%= link_to @company.name, tool_path(@company) %>
      <span class="divider">/</span>
    </li>
  <% end %>
  <li class="active"><%= t(".view_all_brands") %></li>
</ul>

<div class="row-fluid">
  <div class="span12 brand_search_form">
    <form class="well form-search" action="<%= brands_path %>">
      <input type="search" class="input-medium search-query" value="<%= params[:search] %>" results="0" name="search" placeholder="<%= t('.type_your_search_here') %>">
      <button type="submit" class="btn"><%= t("search") %></button>
      <%= hidden_field_tag :company, @company.id if @company %>
      <%= hidden_field_tag :order, params[:order] %>
      <%= link_to t(".add_brand"), new_brand_path, :remote => true, :class => "btn btn-info right" %>
    </form>
  </div>
</div>

<div class="row-fluid">
  <div class="span12 brand_table">
    <h4><%= t(".all_brands") %></h4>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th class="user_column">
            <%= link_to "#{t(".user")} #{params[:order] == 'ASC' ? '&#x25be' : '&#x25b4' }".html_safe, brands_path(:company => params[:company], :search => params[:search], :order => params[:order] == "ASC" ? "DESC" : "ASC") %>
          </th>
          <th class="information_column"><%= t(".information") %></th>
          <th class="similar_column"><%= t(".similar_profiles") %></th>
          <th><%= t(".options") %></th>
        </tr>
      </thead>
      <tbody>
        <%- @brands.each do |brand| %>
          <tr>
            <td>
              <%= image_tag brand.logo, :size => "50x50", :alt => brand.logo, :class => "user_logo" %>
              <p class="user_name">
                <%= brand.name.truncate(25) %>
              </p>
            </td>
            <td>
              <%- brand.locations.each do |location| %>
                <p><%= location.short_address %></p>
              <% end %>
            </td>
            <td></td>
            <td class="last_column">
              <%= link_to t(".view_profile"), tool_path(brand), :class => "btn" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/brands/new.js.erb
$("#bootstrap_modal").html("<%= escape_javascript(render :partial =>'brand') %>");
$("#bootstrap_modal").modal();