config/routes.rb
require 'resque/server'

Beanstock::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  mount Resque::Server.new, :at => "/resque"

  match "/login" => "sessions#new"
  match "/logout" => "sessions#destroy", :as => :logout
  match "/auth/linkedin/callback" => "sessions#create", provider: 'linkedin'
  match "/auth/:provider/callback" => "authorizations#create"

  namespace :signup do
    resources :experiences, :except => [:new, :create, :show]
    resources :users, :only => [:edit, :update]
    resources :skills, :except => [:new, :show]
    resources :beanstock_connections, :only => [:index, :create]
    resources :linkedin_connections, :only => [:index, :create]
  end

  match '/invitations' => 'invitations#update', :as => :invitations
  match 'audiences/autocomplete' => 'audiences#autocomplete', :as => :autocomplete_audiences
  match 'categories/autocomplete' => 'categories#autocomplete', :as => :autocomplete_categories
  match 'sites/autocomplete' => 'sites#autocomplete', :as => :autocomplete_sites
  match 'networks/autocomplete' => 'networks#autocomplete', :as => :autocomplete_networks

  resources :searches, :only => [:index] do
    collection do
      get :autocomplete
    end
  end

  match 'opportunity/1' => 'opportunities#show', :as => :demo_view_opportunity
  match 'opportunities' => 'opportunities#index'
  match 'opportunities/new' => 'opportunities#new', :as => :demo_new_opportunity

  resources :tools, :only => [:index, :show], :path => :connections do
    collection do
      get :new_entry
      get :nice_filter
      post :fine_fetch
    end
  end

  resources :activity_feeds, :only => :index

  resources :conversations, :only => [:index, :show, :new, :create], :path => :messages do
    collection do
      get :add_chat_message
      get :chat_history
      get :autocomplete
      get :archived
      get :window
      get :friend_preview_popup
    end
    member do
      post :quick_reply
      get :forward
      get :new_reply
      post :create_reply
      get :trash
      get :untrash
      get :archive
      get :unarchive
    end

  end

  resources :addresses, :except => [:index]
  resources :agencies do
    collection do
      get 'autocomplete'
    end
  end
  resources :brands do
    collection do
      get 'autocomplete'
    end
  end
  resources :advertisers do
    collection do
      get 'autocomplete'
    end
  end
  resources :buyers
  resources :publishers do
    resources :packages
  end
  resources :circles, :except => [:index, :show] do
    member do
      get 'add_user'
      get 'delete_user'
      get 'confirm_delete'
      get 'show_expanded'
    end
    collection do
      get 'collapse_expanded'
    end
  end
  resource :clicks
  resources :comments do
    resources :likes, :only => [:index, :create]
  end
  resources :answers do
    resources :likes, :only => [:index, :create]
  end
  resources :contacts, :except => [:index]
  resources :connections, :except => [:destroy], :path => :collaborate do
    collection do
      get 'add_contacts'
      get 'search'
    end
  end

  scope :module => "connections" do
    resources :manage_connections do
      collection do
        get "invite_users"
        get "co_workers"
        get "beanstock_connections"
        get "linkedin_connections"
      end
    end
    resources :my_connections do
      collection do
        get "all_connections"
        get "full_user_profile"
      end
    end
    resources :blocked_connections do
      collection do
        get "block_user"
        get "block_autocomplete_user"
        get "unblock_user"
        get "blocked_users"
      end
    end
    resources :ignored_connections
  end

  resources :experiences
  resources :user_profiles, :only => [:show] do
    member do
      get :edit_base_info
      put :update_base_info
      get :popup_profile
      post :update_photo
    end
    resources :viewings, :only => [:index]
  end
  resources :users, :only => [:show, :update] do
    collection do
      get 'show_users'
      get 'new_users_modal'
      get 'update_activity_feed'
      get 'search_friends'
      get 'update_status'
    end
    resources :authorizations
    resources :packages
  end
  resources :notices, :only => [:index, :destroy], :path => :notifications do
    collection do
      get :destroy_all
    end
  end
  resources :requests, :only => [:index]
  resources :suggestions, :only => :index
  resources :news, :as => "news_items", :only => [:index, :show] do
    resources :comments, :only => [:create, :destroy, :update]
    resources :likes, :only => [:index, :create]
    member do
      get :show_news, :as => :show
    end
  end
  match 'slide_elements' => 'news#slide_elements'
  match 'feeds' => 'news#feeds'
  match 'slide_news' => 'news#slide_news'
  resources :posts do
    resources :answers, :only => [:create, :destroy]
    resources :comments, :only => [:create, :destroy, :update]
    resources :likes, :only => [:index, :create]
  end
  resources :settings, except: [:new, :create, :destroy]
  resources :shares, only: [:create]
  resources :timeline_events do
    member do
      get :hide
    end
    collection do
      get :bulk_hide
      get :undo_bulk_hide
    end
  end
  resource :feature_requests, :controller => 'jira_issues', :only => [:new, :create], :type => 'FeatureRequest'
  resource :support_requests, :controller => 'jira_issues', :only => [:new, :create], :type => 'SupportRequest'

  match 'home' => 'users#show'

  root :to => "tools#index"

  unless Rails.env.production?
    match "/all_logins" => "logins#index"
    match "/simulate_login/:id" => "logins#simulate_login", :as => :simulate_login
  end
end

app/models/authorization.rb
# -*- coding: utf-8 -*-
# modeling very simple relationships and making sure that the
# Authorization has both a provider (e.g. “twitter” or “facebook”) and
# a uid (i.e. the external service ID) e.g. twitter's key for your
# account.
class Authorization < ActiveRecord::Base
  belongs_to :user
  belongs_to :social_network, :foreign_key => :provider
  delegate :name, :to => :social_network, :prefix => true

  validates_presence_of :user_id, :uid, :provider
  validates_uniqueness_of :uid, :scope => :provider
  validates_uniqueness_of :provider, :scope =>  :user_id

  def self.create_or_refresh_omniauth(auth, user)
    authorization = find_by_provider_and_uid(auth['provider'], auth['uid'])
    if (authorization.nil?)
      authorization = self.create_with_omniauth(auth, user)
    else
      authorization.refresh(auth)
    end
    authorization
  end

  # return the authorization object for this provider/user
  def self.find_with_omniauth(auth)
    find_by_provider_and_uid(auth[:provider], auth[:uid])
  end

  def self.create_with_omniauth(auth, user)
    name = auth[:info][:nickname] && "@"+auth[:info][:nickname] || auth[:info][:name] # twitter username or name.
    url = auth[:info][:urls].values.compact[0] if auth[:info][:urls] #twitter has one nil
    a=self.create(:user => user,
      :provider => auth[:provider],
      :username => name,
      :profile_url => url,
      :posting_default => true,
      :uid => auth['uid'],
      :oauth_token => auth['credentials']['token'],
      :oauth_token_secret => auth['credentials']['secret'])
    self.configure_gems(auth)
  end

  def refresh(auth)
    username= auth[:nickname]
    uid=auth['uid']
    oauth_token=auth['provider']['token']
    oauth_token_secret= auth['provider']['secret']
  end

  def self.providers(user)
    where(:user_id => user).map {|a| a.provider }
  end

  def self.default_providers(user)
    where(:user_id => user, :posting_default => true).map {|a| a.provider }
  end



  protected

  def self.configure_gems(auth)
    case auth['provider']
    when 'twitter'
      Twitter.configure do |config|
        config.oauth_token = auth['credentials']['token']
        config.oauth_token_secret = auth['credentials']['secret']
      end
    end
  end

end

app/controllers/authorizations_controller.rb
class AuthorizationsController < ApplicationController
  #before_filter :admin_only, only: [:index, :show]


  # GET /authorizations/new
  # GET /authorizations/new.json
  def new
    @social_network = SocialNetwork.find(params[:social_network_id]) # aka :provider since provider is the id.
    @authorization = Authorization.new
    @authorization.provider = @social_network
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @authorization }
    end
  end

  # GET /authorizations/1/edit
  def edit
    @authorization = Authorization.find(params[:id])
  end

  # POST /authorizations
  # POST /authorizations.json

  def create
    auth = request.env['omniauth.auth']
    Authorization.create_or_refresh_omniauth(auth, current_user)
    respond_to do |format|
      format.html { redirect_to edit_setting_url(current_user), :notice => 'Authorized to ' + auth[:provider]}
      format.json { head :no_content }
    end

  end


  # PUT /authorizations/1

  # PUT /authorizations/1.json
  def update
    @authorization = Authorization.find(params[:id])

    respond_to do |format|
      if @authorization.update_attributes(params[:authorization])
        format.html { redirect_to [current_user, @authorization], :notice => 'Authorization was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => 'edit' }
        format.json { render :json => @authorization.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /authorizations/1
  # DELETE /authorizations/1.json
  def destroy
    @authorization = Authorization.find(params[:id])
    message="Disconnected from #{@authorization.social_network_name}"
    @authorization.destroy

    respond_to do |format|
      format.html { redirect_to edit_setting_url(current_user), :notice => message }
      format.json { head :no_content }
    end
  end
  # ADMIN - convenience routines
  # GET /authorizations
  # GET /authorizations.json
  def index

      @authorizations = Authorization.all

      respond_to do |format|
        format.html # index.html.erb
        format.json { render :json => @authorizations }
      end
  end

  # GET /authorizations/1
  # GET /authorizations/1.json
  def show
      @authorization = Authorization.find(params[:id])

      respond_to do |format|
        format.html # show.html.erb
        format.json { render :json => @authorization }
      end
    end
end

app/views/authorizations/_form.html.haml
= form_for @authorization do |f|
  -if @authorization.errors.any?
    #error_explanation
      %h2= "#{pluralize(@authorization.errors.count, "error")} prohibited this authorization from being saved:"
      %ul
        - @authorization.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :user_id
    = f.number_field :user_id
  .field
    = f.label :provider
    = f.number_field :provider
  .field
    = f.label :posting_default
    = f.check_box :posting_default
  .field
    = f.label :username
    = f.text_field :username
  .field
    = f.label :uid
    = f.text_field :uid
  .field
    = f.label :oauth_token
    = f.text_field :oauth_token
  .field
    = f.label :oauth_token_secret
    = f.text_field :oauth_token_secret
  .actions
    = f.submit 'Save'

app/views/authorizations/edit.html.haml
%h1 Editing authorization

= render 'form'

= link_to 'Show', @authorization
\|
= link_to 'Back', authorizations_path

app/views/authorizations/index.html.haml
%h1 Listing authorizations

%table
  %tr
    %th User
    %th Social network
    %th Posting default
    %th Username
    %th Uid
    %th Oauth token
    %th Oauth token secret
    %th
    %th
    %th

  - @authorizations.each do |authorization|
    %tr
      %td= "#{authorization.user.first_name} (#{authorization.user.id})"
      %td= "#{authorization.social_network.name} (#{authorization.social_network.id})"
      %td= authorization.posting_default
      %td= authorization.username
      %td= authorization.uid
      %td= authorization.oauth_token
      %td= authorization.oauth_token_secret
      %td= link_to 'Show', authorization
      %td= link_to 'Edit', edit_authorization_path(authorization)
      %td= link_to 'Destroy', authorization, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Authorization', new_user_authorization_path

app/views/authorizations/new.html.haml
%h1 
  = "Authorize #{@social_network.name}"

%p
  = "Please log into your #{@social_network.name} account to connect #{@social_network.name} to Beanstock"
%p
  = link_to "log into  #{@social_network.name}", "/auth/#{@social_network.provider}"
  
  

= link_to 'Back', user_authorizations_path

app/views/authorizations/show.html.haml
%p#notice= notice

%p
  %b User:
  = @authorization.user_id
%p
  %b Social network:
  = @authorization.provider
%p
  %b Posting default:
  = @authorization.posting_default
%p
  %b Username:
  = @authorization.username
%p
  %b Uid:
  = @authorization.uid
%p
  %b Oauth token:
  = @authorization.oauth_token
%p
  %b Oauth token secret:
  = @authorization.oauth_token_secret

= link_to 'Edit', edit_user_authorization_path(@authorization)
\|
= link_to 'Back', user_authorizations_path